version: 1
formatters:
  simple:
    format: '%(asctime)s.%(msecs)03d - [%(name)s/%(levelname)s]: %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  <train>:
    level: DEBUG
    handlers: [console]
    propagate: no
  dev:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]